# Generated by Django 4.2 on 2025-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('lantupay', '蓝兔支付')], default='lantupay', max_length=50, unique=True, verbose_name='支付提供商')),
                ('merchant_id', models.CharField(max_length=50, verbose_name='商户号')),
                ('api_key', models.CharField(max_length=100, verbose_name='API密钥')),
                ('api_url', models.URLField(default='https://api.ltzf.cn/api/wxpay/jump_h5', max_length=255, verbose_name='API地址')),
                ('notify_url', models.URLField(max_length=255, verbose_name='支付回调通知地址')),
                ('return_url', models.URLField(max_length=255, verbose_name='支付成功跳转地址')),
                ('quit_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='取消支付跳转地址')),
                ('expire_time', models.CharField(default='5m', max_length=10, verbose_name='订单过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付配置',
                'verbose_name_plural': '支付配置列表',
            },
        ),
        migrations.AddField(
            model_name='chargerecord',
            name='payment_data',
            field=models.JSONField(blank=True, null=True, verbose_name='支付数据'),
        ),
        migrations.AddField(
            model_name='chargerecord',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='支付链接'),
        ),
        migrations.AlterField(
            model_name='chargerecord',
            name='payment_method',
            field=models.CharField(choices=[('lantupay', '蓝兔支付')], default='lantupay', max_length=50, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='chargerecord',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('paid', '已支付'), ('approved', '已通过'), ('rejected', '已拒绝'), ('canceled', '已取消'), ('failed', '支付失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ] 