# Generated by Django 4.2 on 2025-04-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_init_default_service_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=50, unique=True, verbose_name='模型ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('api_provider', models.CharField(default='openai', max_length=50, verbose_name='API提供商')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['display_order', 'model_id'],
            },
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, verbose_name='频率惩罚'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='max_tokens',
            field=models.IntegerField(default=1500, verbose_name='最大令牌数'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='model',
            field=models.CharField(default='gpt-4o', max_length=50, verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='presence_penalty',
            field=models.FloatField(default=0.0, verbose_name='存在惩罚'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='top_p',
            field=models.FloatField(default=1.0, verbose_name='Top P值'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(default='gpt-4o', max_length=50, verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='新对话', max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='所属对话'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=10, verbose_name='角色'),
        ),
        migrations.AddConstraint(
            model_name='chatsetting',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_setting'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='chat.aiserviceprovider', verbose_name='服务商'),
        ),
    ]
