# Generated by Django 4.2 on 2025-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_update_service_provider_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='max_context_length',
            field=models.IntegerField(default=4096, verbose_name='最大上下文长度'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_audio',
            field=models.BooleanField(default=False, verbose_name='支持音频处理'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_file_analysis',
            field=models.BooleanField(default=False, verbose_name='支持文件分析'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_image_analysis',
            field=models.BooleanField(default=False, verbose_name='支持图片分析'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_image_generation',
            field=models.BooleanField(default=False, verbose_name='支持图片生成'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_stream',
            field=models.BooleanField(default=True, verbose_name='支持流式响应'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_web_search',
            field=models.BooleanField(default=False, verbose_name='支持联网搜索'),
        ),
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token数'),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token数'),
        ),
    ]
