# Generated by Django 4.2 on 2025-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_aimodel_max_context_length_aimodel_supports_audio_and_more'),
        ('chat', 'manual_migration'),
    ]

    operations = [
    ]
