# Generated by Django 4.2 on 2025-05-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_add_missing_fields_aimodel'),
        ('chat', 'add_supports_reasoning'),
    ]

    operations = [
    ]
