# Generated by Django 4.2 on 2025-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_merge_20250512_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['sort_order', 'model_id'], 'verbose_name': 'AI模型', 'verbose_name_plural': 'AI模型列表'},
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='api_provider',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='max_context_length',
            field=models.IntegerField(default=8000, verbose_name='最大上下文长度'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序顺序'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='supports_image_analysis',
            field=models.BooleanField(default=False, verbose_name='支持图像分析'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='supports_image_generation',
            field=models.BooleanField(default=False, verbose_name='支持图像生成'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='supports_web_search',
            field=models.BooleanField(default=False, verbose_name='支持网络搜索'),
        ),
        migrations.DeleteModel(
            name='AIServiceProvider',
        ),
    ]
