# Generated by Django 4.2 on 2025-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_aimodel_options_remove_aimodel_api_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_endpoint',
            field=models.CharField(blank=True, help_text='可以为每个模型设置独立的API请求端点，留空则使用服务商默认端点', max_length=255, null=True, verbose_name='API请求端点'),
        ),
    ]
