# Generated by Django 4.2 on 2025-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_has_image_message_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='最后活动时间'),
        ),
    ]
