# Generated by Django 4.2 on 2025-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_conversation_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='AI提示词'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='系统提示词'),
        ),
    ]
