# Generated by Django 4.2 on 2025-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_add_ai_prompt_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='ai_prompt',
            field=models.TextField(blank=True, default='你是一位专业、有帮助的人工智能助手，始终提供准确、有用的信息。', null=True, verbose_name='AI提示词'),
        ),
    ]
