# Generated by Django 4.2 on 2025-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_add_default_ai_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(blank=True, help_text='设置所有用户共用的系统提示词，这将覆盖用户级别的系统提示词设置', null=True, verbose_name='全局系统提示词')),
                ('default_ai_prompt', models.TextField(blank=True, help_text='设置新用户的默认AI提示词', null=True, verbose_name='默认AI提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局设置',
                'verbose_name_plural': '全局设置',
            },
        ),
    ]
