# Generated by Django 4.2 on 2025-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片路径'),
        ),
    ]
